version: '3.8'

services:
  user_db:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_user_db
    restart: unless-stopped
    ports:
      - "5438:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product_db:
    image: postgres:latest
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_product_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction_db:
    image: postgres:latest
    container_name: postgres-transaction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_transaction_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  merchant_db:
    image: postgres:latest
    container_name: postgres-merchant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_merchant_db
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - postgres_merchant_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification_db:
    image: postgres:latest
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_notification_db
    restart: unless-stopped
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse_db:
    image: postgres:latest
    container_name: postgres-warehouse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_warehouse_db
    restart: unless-stopped
    ports:
      - "5437:5432"
    volumes:
      - postgres_warehouse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: warehouse_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: warehouse_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_user_data:
  postgres_product_data:
  postgres_transaction_data:
  postgres_merchant_data:
  postgres_notification_data:
  postgres_warehouse_data: